name: snyk-labs/action example - Snyk Issues to Github Issues
on: workflow_dispatch
  # - push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: snyk/actions/setup@master
      - uses: actions/setup-node@v1
      - name: snyk test
        run: snyk test --all-projects --severity-threshold=high --sarif-file-output=snyk.sarif
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      - uses: snyk-labs/actions/sarif-to-gh-issues@main
        with:
          sarif_file: snyk.sarif
        env:
          GITHUB_TOKEN: ${{ github.token }}
          REMOTE_REPO_URL: ${{ github.repositoryUrl }}
          
